/* Lógico_LAB_5: */

--> TABELAS DE DOMÍNIO
CREATE TABLE SEXO (
    ID_SEXO NUMBER(1) PRIMARY KEY,
    DESCRICAO_SEXO VARCHAR2(15) NOT NULL
);

CREATE TABLE RACA_COR (
    ID_RACA_COR NUMBER(1) PRIMARY KEY,
    DESCRICAO_RACA_COR VARCHAR2(20) NOT NULL
);

--> TABELA DE MUNICÍPIO
CREATE TABLE MUNICIPIO (
    COD_MUNICIPIO NUMBER(7) PRIMARY KEY,
    NOME_MUNICIPIO VARCHAR2(100) NOT NULL,
    UF CHAR(2) NOT NULL,
    REGIAO VARCHAR2(20)
);

ALTER TABLE MUNICIPIO ADD CONSTRAINT CK_MUNICIPIO_UF
CHECK (LENGTH(UF) = 2);

--> TABELAS CID-10
CREATE TABLE CAPITULO_CID (
    ID_CAPITULO NUMBER(2) PRIMARY KEY,
    COD_CAPITULO VARCHAR2(3) NOT NULL,
    DESCRICAO_CAPITULO VARCHAR2(150) NOT NULL
);

CREATE TABLE CAUSA_OBITO (
    CID_COD VARCHAR2(4) PRIMARY KEY,
    CID_DESCRICAO VARCHAR2(255),
    ID_CAPITULO NUMBER(2) NOT NULL
);

ALTER TABLE CAUSA_OBITO ADD CONSTRAINT FK_CID_CAPITULO
    FOREIGN KEY (ID_CAPITULO)
    REFERENCES CAPITULO_CID (ID_CAPITULO);

--> TABELA PRINCIPAL – OBITO
CREATE TABLE OBITO (
    ID_OBITO NUMBER(10) PRIMARY KEY,
    ANO_OBITO NUMBER(4) NOT NULL,
    MES_OBITO NUMBER(2) NOT NULL,
    DIA_OBITO NUMBER(2),
    IDADE_ANOS NUMBER(3),
    FAIXA_ETARIA VARCHAR2(10),
    ID_SEXO NUMBER(1) NOT NULL,
    ID_RACA_COR NUMBER(1),
    COD_MUNICIPIO_RES NUMBER(7),
    COD_MUNICIPIO_OCOR NUMBER(7),
    CID_COD VARCHAR2(4) NOT NULL
);

--> CONSTRAINTS DE INTEGRIDADE
ALTER TABLE OBITO ADD CONSTRAINT FK_OBITO_SEXO
    FOREIGN KEY (ID_SEXO)
    REFERENCES SEXO (ID_SEXO);

ALTER TABLE OBITO ADD CONSTRAINT FK_OBITO_RACA
    FOREIGN KEY (ID_RACA_COR)
    REFERENCES RACA_COR (ID_RACA_COR);

ALTER TABLE OBITO ADD CONSTRAINT FK_OBITO_MUN_RES
    FOREIGN KEY (COD_MUNICIPIO_RES)
    REFERENCES MUNICIPIO (COD_MUNICIPIO);

ALTER TABLE OBITO ADD CONSTRAINT FK_OBITO_MUN_OCOR
    FOREIGN KEY (COD_MUNICIPIO_OCOR)
    REFERENCES MUNICIPIO (COD_MUNICIPIO);

ALTER TABLE OBITO ADD CONSTRAINT FK_OBITO_CID
    FOREIGN KEY (CID_COD)
    REFERENCES CAUSA_OBITO (CID_COD);

--> CHECK CONSTRAINTS
ALTER TABLE OBITO ADD CONSTRAINT CK_OBITO_MES
CHECK (MES_OBITO BETWEEN 1 AND 12);

ALTER TABLE OBITO ADD CONSTRAINT CK_OBITO_DIA
CHECK (DIA_OBITO BETWEEN 1 AND 31 OR DIA_OBITO = -1);

--> ÍNDICES (DESEMPENHO)
CREATE INDEX IDX_OBITO_CID ON OBITO (CID_COD);
CREATE INDEX IDX_OBITO_MUN_RES ON OBITO (COD_MUNICIPIO_RES);
CREATE INDEX IDX_OBITO_MUN_OCOR ON OBITO (COD_MUNICIPIO_OCOR);
CREATE INDEX IDX_OBITO_SEXO ON OBITO (ID_SEXO);
CREATE INDEX IDX_OBITO_RACA ON OBITO (ID_RACA_COR);